### ISSUE TITLE
REQ: installation documentation for configuring multiple netapps for cinder

### ISSUE THREAD

**Issue by toxick** [rpcdocs/docs-issues#19]
SSIA

**Comment by odyssey4me** [comment]
What does SSIA mean?

**Comment by odyssey4me** [comment]
Reference information:
 - Icehouse/9.x: http://docs.openstack.org/icehouse/config-reference/content/netapp-volume-driver.html
 - Juno/10.x: http://docs.openstack.org/juno/config-reference/content/netapp-volume-driver.html
 - http://docs.openstack.org/admin-guide-cloud/content/multi_backend.html

Typically you would have something like the following in cinder.conf, assuming that you're using iSCSI and each NetApp is a single device (not a cluster) and is 7mode.

```
enabled_backends=netapp1,netapp2

[netapp1]
volume_backend_name=netapp1_sas
volume_driver=cinder.volume.drivers.netapp.common.NetAppDriver
netapp_storage_family=ontap_7mode
netapp_storage_protocol=iscsi
netapp_server_hostname=10.12.26.21
netapp_server_port=80
netapp_login=netapp_openstackuser
netapp_password=netapp_openstackpassword
[netapp2]
volume_backend_name=netapp2_sata
volume_driver=cinder.volume.drivers.netapp.common.NetAppDriver
netapp_storage_family=ontap_7mode
netapp_storage_protocol=iscsi
netapp_server_hostname=10.12.26.22
netapp_server_port=80
netapp_login=netapp_openstackuser
netapp_password=netapp_openstackpassword
```

With this in place, the following commands need to be executed in order to register the volume types which are made available to end-users:

```
cinder type-create "NetApp SAS"
cinder type-key "NetApp SAS" set volume_backend_name=netapp1_sas
cinder type-create "NetApp SATA"; \
cinder type-key "NetApp SATA" set volume_backend_name=netapp2_sata
```

If a user does not select a volume type when creating a volume, then the first volume backend in the enabled backends list is used.

**Comment by klevenstein** [comment]
SSIA = "Subject Says It All" :)

Thanks for the assist; will work on getting this into the docs.

**Comment by darrenchan** [comment]
NetApp Deployment and Operations Guide (Icehouse): http://community.netapp.com/fukiw75442/attachments/fukiw75442/virtualization-and-cloud-articles-and-resources/450/1/openstack-deployment-ops-guide.pdf

**Comment by darrenchan** [comment]
@odyssey4me do you mean editing the rpc_user_config.yml file?  For example, in  https://github.com/stackforge/os-ansible-deployment/blob/juno/etc/rpc_deploy/rpc_user_config.yml.example#L160
 you would replace the lvm and lvm_ssd  backends with netapp1 and netapp2 and add the back end parameters?

**Comment by odyssey4me** [comment]
@darrenchan My note was how to configure cinder itself directly, but it looks like your suggestion to edit the user_config is correct and will result in the appropriate cinder configuration file.
