### ISSUE TITLE
Add documentation on host_networks configuration

### ISSUE THREAD

**Issue by cfarquhar** [rpcdocs/docs-issues#24]
Please add documentation on how to configure host networking using the stanzas shown in the example rpc_user_config.yml [1]. After adding these stanzas to the configuration, which playbook uses them and where will the resulting config files be created?  Are the playbooks that use this configuration idempotent?

[1] https://github.com/stackforge/os-ansible-deployment/blob/master/etc/rpc_deploy/rpc_user_config.yml.example#L143-L151

**Comment by nrb** [comment]
The playbook that uses these values is ```roles/host_interfaces``` and they are inserted into the ```templates/interfaces_gen.j2``` file within that role. The generated file is *not* enabled by default; it has to be reviewed then manually sourced with ```/etc/network/interfaces```, and the interfaces taken down/brought up. However, if the ```conf.d``` directory is sourced, then it will be read the next time the interfaces are brought up.

The file is idempotent, however we've discovered a number of bugs when this interfaces file is created and used.

This playbook isn't documented, and I personally am for removing it/the examples entirely. It initially seemed helpful, but I think that it's better for the deployer to manually configure interfaces long term.

**Comment by ionosphere80** [comment]
Can you comment, @cloudnull?

**Comment by cfarquhar** [comment]
Manual configuration of 60+ (or potentially hundreds) of nodes is tedious and error prone.  Ideally, there would be a mechanism to ease this burden, including automatic allocation of the bridge IPs.

**Comment by nrb** [comment]
That is true - as it stands, the interface_gen.j2 is pretty dumb. There conditionals for the interface type, but the data is pretty much all required to be entered manually in the config files.

If we keep this around, I think we should prioritize making it a little smarter, possibly an actual ansible module, since as it stands it's fairly limited. And document it, of course.

**Comment by nrb** [comment]
For reference, there is https://galaxy.ansible.com/list#/roles/3, which is also entirely manual, just YAML instead of ifupdown.

There's also the debops.ifupdown role, but that seems limited to one or two interfaces. (https://galaxy.ansible.com/list#/roles/1570)

A better question - what were you hoping the script did? Or, to put another way, what's the most annoying part of the interface creation during a real deploy?

**Comment by ionosphere80** [comment]
Any updates here?

**Comment by nrb** [comment]
I have proposed a [blueprint](https://blueprints.launchpad.net/openstack-ansible/+spec/improved-network-generation) - it relies on using the debops.ifupdown role, which after some more investigation appears like it could support our use case.

I am going to work on integrating this with our process as a spike and gather feedback on this, though, since it would require some overhaul of existing roles/scripts.

**Comment by asettle** [comment]
@cfarquhar and @nrb - is this still relevant for 11.0+?

Thanks

**Comment by nrb** [comment]
I would say no: we removed the playbook mentioned in Kilo, and after some experiments with other implementations, decided to leave host networking out of the OSA/rpc-openstack scope.

**Comment by asettle** [comment]
Thank you @nrb - since this is over a year old now, closing. 
CCing @klevenstein
