### ISSUE TITLE
Internal Install Guide v9 & v10 - need to add maas_cdm play

### ISSUE THREAD

**Issue by russwclark** [rpcdocs/docs-issues#27]
The current list of plays to run for monitoring does not include the maas_cmd play.  Please update the installation document to include the running of this play during the deployment.

"Rackspace Private Cloud Installation Guide  - RPC v9.0.3
Procedure 10.1. Running the playbooks"

**Comment by claco** [comment]
The changes in the rpc-maas code also have an upgrade impact.

Some of the metrics names were corrected. This means that the release versions of 10.1.2 and 9.0.6 will need to be pointed at the correct version of rpc-maas in config. There will also have to be some upgrade steps involved since the maas checks won't be updated upstream until they're first deleted by the operator before running the playbook.

https://bugs.launchpad.net/openstack-ansible/+bug/1415542
https://github.com/rcbops/rpc-maas/pull/145

**Comment by klevenstein** [comment]
cc: @ionosphere80 re: upgrade documentation

**Comment by ionosphere80** [comment]
@claco Do we have an environment with MaaS that we can upgrade and document the procedure? Looking at changes between v9 and v10, I mentioned removal of the "maas_repo_version" option in user_variables.yml file in the upgrade content.

**Comment by claco** [comment]
Adding @mancdaz @mattt416  for https://github.com/rcbops/rpc-maas/commit/b05d0d1b98171c5594cde735d4921b86bb86d35d

Not sure if the plan is to run ansibles, ther maas play, then run the script matt added to delete the then defunked older checks/alarms.

**Comment by mancdaz** [comment]
@clack instructions were added to the docs on what alarms to delete manually if upgrading to 9.0.6 or 10.1.2

We haven't documented use of the tool to do the same

**Comment by mancdaz** [comment]
@claco instructions were added to the docs on what alarms to delete manually if upgrading to 9.0.6 or 10.1.2

We haven't documented use of the tool to do the same

**Comment by ionosphere80** [comment]
Any updates?

**Comment by mancdaz** [comment]
@ionosphere80 @claco @mattt416 I'd suggest just leaving it with the instructions on what to delete.  We've not fully tested the script, and incorrect use of that script could end up removing a lot of things we didn't want to remove.

**Comment by klevenstein** [comment]
Lots of changes have been made to the maas chapter and the update chapter; this has probably been addressed by now?
