### ISSUE TITLE
Document eventlet breakage in v9 release notes

### ISSUE THREAD

**Issue by klevenstein** [rpcdocs/docs-issues#31]
See https://bugs.launchpad.net/openstack-ansible/+bug/1419453 for details
Will be fixed in 9.0.7; meanwhile add to the v9 Known Issues list.

**Comment by darrenchan** [comment]
Should we add this to the v10 release notes as well? It also affects Juno: https://bugs.launchpad.net/nova/+bug/1407685

**Comment by klevenstein** [comment]
Investigating; stay tuned.

**Comment by klevenstein** [comment]
Okay, it looks like RPC v10 is not affected in the same way: https://bugs.launchpad.net/openstack-ansible/+bug/1419453/comments/4

**Comment by sigmavirus24** [comment]
So this should be a "Known issue", it may not be an issue on v10 only because the repos are frozen in versions prior to 10.1.2 and 10.1.2's packages (on mirror.rackspace.com) was built without `eventlet>=0.16` (and as such shouldn't be affected).

9.0.7 will be the first version after upstream placed an upper limit on eventlet.

**Comment by klevenstein** [comment]
Okay, we've documented this in the v9 release notes:
http://docs-staging.rackspace.com/rpc/api/v9/bk-rpc-releasenotes/content/known-issues.html
So closing this issue. We'll remove it from the Known Issues list when v9.0.7 happens.
