### ISSUE TITLE
SOFTWARE RELEASE NOTES, V10, Chapter 4, "Upgrading": Suggest additional disclaimer for < 9.0.3 -> 10.1.x instruction

### ISSUE THREAD

**Issue by IRTermite** [rpcdocs/docs-issues#33]
Currently, "This chapter describes the process for upgrading an environment between major releases, and minor releases. The currently supported major upgrade scenario is from version 9.0.3 or later to 10.1.x."

What of systems that are less than 9.0.3, say ones with 9.0.2 with manual patches?  It should go without saying that unless they are on 9.0.3 they need to upgrade, but not everyone can infer the next steps...

1) Do they simply update to 9.0.3 first?
2) What about the cases with manual patches versus not?

**Comment by ionosphere80** [comment]
I think we're trying to minimize the number of upgrade permutations because each one requires an additional round of documentation and testing. Ideally, our product should support upgrading from any major.minor.fix version to the current release of the next major version. For example, 9.0.x to 10.1.2. However, as I understand the situation, growing pains in early 9.x releases prevent cleanly upgrading directly to 10 from versions prior to 9.0.3, perhaps due to manual patches causing unique situations that require special attention. How many customers do we have in this situation and how different are their installations?

**Comment by IRTermite** [comment]
Makes sense, but we aren't really asking for numerous counts of documentation for upgrade paths; mostly just making sure to CYA the wording for those who will ask "it says 9.0.3 to 10.x; what do I if I am on a lesser version?"  I just want to make sure that we call out whether they need to worry about being on a lesser version, or if there are indeed actual steps.

Customer versions are all over the place, as they all schedule and change on their own timing.  We are doing this on an environment with manuals now...

However, cloudnull just had us go from 9.0.2 directly to 10.1.2rc1, stating that path will completely solve the concerns we have.

**Comment by ionosphere80** [comment]
When I wrote the initial upgrade content, only 9.0.3 and 9.0.5+ were validated for upgrade to 10.1. If the development and/or QE teams upgraded a 9.0.2 environment (with manual patches?) to 10.1.2rc1, I can update the requirements to reflect it. If they can validate enough versions of 9 to cover the majority of customers, the impact of this issue decreases considerably.

**Comment by IRTermite** [comment]
I think we just confirmed it possible to upgrade from 9.0.2 to 10.1.2rc1.  Guess we can close this?

**Comment by ionosphere80** [comment]
I'll close this issue with the patch that adds 9.0.2.
