### ISSUE TITLE
Add to v9.0.6 and 10.1.1 release notes: rabbitmq issue

### ISSUE THREAD

**Issue by klevenstein** [rpcdocs/docs-issues#48]
Details: https://bugs.launchpad.net/openstack-ansible/+bug/1427011

**Comment by darrenchan** [comment]
@klevenstein isn't this a known issue for 9.0.6? If I'm reading https://bugs.launchpad.net/openstack-ansible/+bug/1427011 correctly, Jesse mentions it will be fixed for 9.0.7 under comment #1?

**Comment by klevenstein** [comment]
?@odyssey4me can you clarify?

________________________________

**Comment by robb-romans** [comment]
See also ﻿https://github.com/rpcdocs/docs-issues/issues/52

**Comment by robb-romans** [comment]
From @odyssey4me bug comments: "This needs to be listed as a known issue for anything < 9.0.7 and < 10.1.2"

**Comment by odyssey4me** [comment]
Confirmed - this needs to be not d as a known issue for < 9.0.7 (which hasn't been tagged yet) and < 10.1.2. Essentially if the playbooks have been run more recently than 10.1.2's release date, they will do an automatic upgrade of rabbitmq. This will result in the environment having a later version of rabbit than will exist if the deployer tries to deploy 10.1.2.
One workaround is to downgrade. The other is to set the rabbit version variable to whatever the current version is so that it stays in place.
The second workaround, however, means that you'll be running a version of rabbit which hasn't gone through QE testing by RPC.

**Comment by klevenstein** [comment]
https://github.com/rpcdocs/v9/pull/51
