### ISSUE TITLE
Add pre-upgrade version checks for 9.x to 10.x

### ISSUE THREAD

**Issue by klevenstein** [rpcdocs/docs-issues#71]
Copied over from rpcdocs/rpcdocs#18, via @cfarquhar 

> I believe some versions of 9.x need to have packages (e.g. RabbitMQ, oslo.messaging, eventlet) manually downgraded prior to the upgrade. Can we get documentation in the 10.x release notes on what to check for prior to the upgrade?

**Comment by darrenchan** [comment]
We'll need to add this to the v11 release notes as well, for upgrades from v9.

**Comment by darrenchan** [comment]
Info from Jesse:
"Pinning for RabbitMQ was introduced in v9.0.7/v10.1.2 and the pin is to version 3.4.3-1:
https://github.com/stackforge/os-ansible-deployment/blob/9.0.7/rpc_deployment/inventory/group_vars/rabbit.yml#L18
https://github.com/stackforge/os-ansible-deployment/blob/10.1.2/rpc_deployment/inventory/group_vars/rabbit.yml#L18-L20

The version that is being pinned to may be overridden by setting the full rabbitmq_package_url variable in the user config to whatever version the deployer wishes to pin to. The version above is just the default version set.

Any RPC 9.x and RPC 10.x versions below the above may have run their plays after the initial deployment and, as a result, ended up with a later version of RabbitMQ. If this is the case the deployer may either choose to leave the above default set, and the plays will downgrade RabbitMQ, or the deployer may choose to set the newer version as the pin for the environment in the user config."

Info from Bjoern: 
"Along with rabbit there needs to to be the  oslo.messaging library checked and possibly downgraded to.
We did document the oslo.messaging downgrade at https://one.rackspace.com/pages/viewpage.action?pageId=115362257#RPC9and10Tips/Tricks/Issues/FAQs-Downgradingoslo.messagingfrom1.5.1to1.4.1, it’s a bit of a pain since you touch pretty much any container and it is every where used.
Rabbitmq downgrade has been documented at https://one.rackspace.com/pages/viewpage.action?pageId=115362257#RPC9and10Tips/Tricks/Issues/FAQs-Downgradingrabbitmq-serverprior9.0.7or10.1.2RPCrelease"

**Comment by robb-romans** [comment]
Does it apply to minor version upgrades or just v9->v10? Is this issue specific to RPC v9.0.7 and v10.1.3? In other words, do you have to worry about this when installing v9.0.8 and v10.1.4? 

If this is fixed in v9.0.8 and v10.1.4, follow on question is should we discourage using v9.0.7 and v10.1.3?

**Comment by darrenchan** [comment]
@BjoernT @odyssey4me The rabbitmq_package_url variable appears in rabbit.yml, not in user config file previously mentioned. So do we edit the rabbit.yml file, or add the variable to the user config file?

**Comment by BjoernT** [comment]
We added this check for all minor versions, just to make sure.
It primarily will be noticeable starting with 9.0.6 and 10.1.2. So it's safe so say that this version check should be executed at releases < 10.1.2

**Comment by BjoernT** [comment]
@darrenchan No we never edit any rebo vars file. If we would have to override a version for example we would add this token to the user_config.yml and override the repo vars this way

**Comment by darrenchan** [comment]
Thanks @BjoernT. BTW, can you review my patch ^^^ ?

**Comment by darrenchan** [comment]
Information is added to the v11 release notes: https://github.com/rpcdocs/rpcdocs/pull/32
